#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1523619187                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Your new digital cookbook

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Zoltán Dániel Török                                
your_link                                 : https://zdt.hu                     
your_city                                 : Budapest                                
email_address                             : dzsig.92@gmail.com
facebook_username                         : 
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Full synchronization
    description                           : Have your recipes always up-to-date across your devices! It's automatically synchronized.
    fontawesome_icon_name                 : sync

  - title                                 : iPad and iPhone Support
    description                           : Nyamm is available both on your iPhone and iPad!
    fontawesome_icon_name                 : mobile

  - title                                 : Food Groups
    description                           : Organize your recipes into different food groups, so you will find your best recipes easily.
    fontawesome_icon_name                 : burger
    
  - title                                 : External links for your recipes
    description                           : Store a useful link to a website/video for your recipes, so you can get there with one touch.
    fontawesome_icon_name                 : link

  - title                                 : Use your own photos
    description                           : Amaze yourself with beautiful photos:: add your own photos for your recipes and food groups!
    fontawesome_icon_name                 : images

  - title                                 : Easy Share
    description                           : Send your recipe to a friend instantly with one touch, so they can save it in their Nyamm immediately.
    fontawesome_icon_name                 : share

  - title                                 : PDF Export
    description                           : Export your recipes in PDF so you can share or print them later.
    fontawesome_icon_name                 : file-export

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"





####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
